# Generated by Django 5.2.5 on 2025-08-15 20:11

import django.db.models.deletion
import todo.id_gen
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(default=todo.id_gen.snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('user_id', models.BigIntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Telegram Account',
                'verbose_name_plural': 'Telegram Accounts',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'chat_id'), name='unique_user_chat_id')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(default=todo.id_gen.snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='todo.category')),
                ('tg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todo.telegramaccount')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='todo.telegramaccount'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_user_category_name'),
        ),
    ]
