# Generated by Django 5.2.5 on 2025-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='user_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
