# Generated by Django 5.2.5 on 2025-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_telegramaccount_linked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramLinkCode',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TelegramAccount',
        ),
    ]
