# Generated by Django 5.2.5 on 2025-08-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_telegramaccount_user_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='telegramaccount',
            name='unique_user_chat_id',
        ),
    ]
