# Generated by Django 5.2.5 on 2025-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_telegramaccount_unique_user_chat_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_user_category_name',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'tg'), name='unique_category_per_tg'),
        ),
    ]
