# Generated by Django 5.2.5 on 2025-08-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_telegramaccount_user_delete_telegramlinkcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user_id', 'name'), name='unique_user_category_name'),
        ),
    ]
