services:
  crud-django-service:
    build:
      context: ../services/crud-django-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../services/crud-django-service/src:/app/src
    env_file:
      - ../.env
    environment:
      WORKER_ID: 1
    depends_on:
      redis:
        condition: service_started
      postgres-db:
        condition: service_healthy
    entrypoint: ["/app/entrypoint.sh"]
  redis:
    image: redis:alpine
    environment:
      WORKER_ID: 2
    ports:
      - "6379:6379"

  postgres-db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      WORKER_ID: 3
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: todopy_postgres_data