#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_READ_USER}'
   ) THEN
      CREATE ROLE ${POSTGRES_READ_USER} WITH LOGIN PASSWORD '${POSTGRES_READ_PASSWORD}';
      GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READ_USER};
      GRANT USAGE ON SCHEMA todo_db TO ${POSTGRES_READ_USER};
      GRANT SELECT ON ALL TABLES IN SCHEMA todo_db TO ${POSTGRES_READ_USER};
      ALTER DEFAULT PRIVILEGES IN SCHEMA todo_db GRANT SELECT ON TABLES TO ${POSTGRES_READ_USER};
   END IF;
END
\$\$;
EOSQL
